### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by clinkme4g** [briangann/grafana-gauge-panel#19]
Trying to install this plugin to RaspberryPi3 (Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux)  running Grafana version 4.3.2.
After adding the new panel with D3gauge plugin, the error popups with text:
```
Plugin Error
(SystemJS) missing ; before statement Evaluating http://192.168.1.78:3000/public/plugins/briangann-gauge-panel/external/d3gauge.js?bust=1497162865794 Error loading http://192.168.1.78:3000/public/plugins/briangann-gauge-panel/module.js
```
and this panel is marking with error sign "Cannot read property 'updateGauge' of null" and becomes not editable.
Stack trace:
```
TypeError: Cannot read property 'updateGauge' of null
    at D3GaugePanelCtrl.onDataReceived (http://192.168.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js?bust=1497162925274:543:29)
    at f.emit (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:61:19125)
    at a.emit (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:61:21443)
    at D3GaugePanelCtrl.b.handleQueryResult (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:55:20950)
    at i (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:51:24759)
    at http://192.168.1.78:3000/public/app/boot.d709d8d5.js:51:25181
    at o.$eval (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:52:293)
    at o.$digest (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:51:30809)
    at o.$apply (http://192.168.1.78:3000/public/app/boot.d709d8d5.js:52:576)
    at http://192.168.1.78:3000/public/app/boot.d709d8d5.js:51:28669
```
When trying to create a new dashboard with only one D3gauge panel on it (as seen from old issue here), the error popups:
```
Plugin Error
(SystemJS) Block-scoped declarations (let, const, function, class) not yet supported outside strict mode SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode at eval (native) Evaluating http://192.168.1.78:3000/public/plugins/briangann-gauge-panel/external/d3gauge.js?bust=1497163697173 Error loading http://192.168.1.78:3000/public/plugins/briangann-gauge-panel/module.js
```
There is only one Datasource (influxdb on separate machine).

**Comment by clinkme4g** [comment]
It seems that is my client problem. Trying IE from another machine and plugin works as described.
