### ISSUE TITLE
Panel not working in Beta 5.0.0

### ISSUE THREAD

**Issue by lgwapnitsky** [briangann/grafana-gauge-panel#29]
Receiving the following error:

TypeError: Cannot read property 'height' of undefined
    at D3GaugePanelCtrl.getPanelHeight (http://10.101.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js:221:41)
    at D3GaugePanelCtrl.renderGauge (http://10.101.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js:261:37)
    at render (http://10.101.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js:503:20)
    at o.eval (http://10.101.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js:506:15)
    at o.emit (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:44:25754)
    at e.emit (http://10.101.1.78:3000/public/build/app.09ca0886c7c907fe8d09.js:1:12999)
    at D3GaugePanelCtrl.t.render (http://10.101.1.78:3000/public/build/0.7fcd053fbf0c943e1675.js:1:9381)
    at D3GaugePanelCtrl.onDataReceived (http://10.101.1.78:3000/public/plugins/briangann-gauge-panel/ctrl.js:670:20)
    at o.emit (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:44:25321)
    at e.emit (http://10.101.1.78:3000/public/build/app.09ca0886c7c907fe8d09.js:1:12999)
    at D3GaugePanelCtrl.e.handleQueryResult (http://10.101.1.78:3000/public/build/0.7fcd053fbf0c943e1675.js:7:18112)
    at u (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:69119)
    at http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:69565
    at d.$digest (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:75262)
    at d.$apply (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:77076)
    at http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:73135
    at i (http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:21978)
    at http://10.101.1.78:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:23440
![chrome_2018-02-09_14-07-34](https://user-images.githubusercontent.com/647444/36045209-f68ae3f6-0da2-11e8-86a9-fb7971fdbb89.png)

**Comment by briangann** [comment]
I'll get this fixed right away :)

**Comment by privet971** [comment]
with v5.0.0-beta1 (commit: 3e2da1f) on Rpi (armhf)

<img width="747" alt="screenshot" src="https://user-images.githubusercontent.com/26382638/36066761-2150f556-0e86-11e8-9179-a53e5cd5908d.png">

**Comment by judy** [comment]
Looks like it's due to the grid engine being redone in v5.0. Most panels aren't going to be in rows. I'm working on a fix myself.

**Comment by briangann** [comment]
verified working on v3/v4/v5 now, thanks!
