### ISSUE TITLE
D3Gauge error after upgrade to Grafana 5

### ISSUE THREAD

**Issue by KjellRanda** [briangann/grafana-gauge-panel#32]
Hi,
After upgrade to Grafana 5 I get the following errors on all my D3Gauge panels and I am not able to create new one either, they all get the same error.

This is on Fedora 27 with the Fedora package grafana-5.0.0-1.x86_64 installed and D3Gauge version 0.0.5

TypeError: Cannot read property 'height' of undefined
    at D3GaugePanelCtrl.getPanelHeight (http://www.net.home:3000/public/plugins/briangann-gauge-panel/ctrl.js:221:41)
    at D3GaugePanelCtrl.renderGauge (http://www.net.home:3000/public/plugins/briangann-gauge-panel/ctrl.js:261:37)
    at render (http://www.net.home:3000/public/plugins/briangann-gauge-panel/ctrl.js:503:20)
    at o.eval (http://www.net.home:3000/public/plugins/briangann-gauge-panel/ctrl.js:506:15)
    at o.emit (http://www.net.home:3000/public/build/vendor.2c3c591224fb193f7fd3.js:44:25754)
    at e.emit (http://www.net.home:3000/public/build/app.b0d4f36bb5b6bb18e2ab.js:1:13162)
    at D3GaugePanelCtrl.t.render (http://www.net.home:3000/public/build/0.61d63d0094e218376e17.js:1:9381)
    at D3GaugePanelCtrl.onDataReceived (http://www.net.home:3000/public/plugins/briangann-gauge-panel/ctrl.js:670:20)
    at o.emit (http://www.net.home:3000/public/build/vendor.2c3c591224fb193f7fd3.js:44:25321)
    at e.emit (http://www.net.home:3000/public/build/app.b0d4f36bb5b6bb18e2ab.js:1:13162)

Best regards
Kjell Randa

**Comment by briangann** [comment]
You'll need to clone the plugin from this repo for now, the PR on grafana.com hasn't been merged yet.

Thanks!

Brian

**Comment by costimuraru** [comment]
Getting the same error on Grafana 5.

<img width="743" alt="screenshot 2018-03-04 01 20 29" src="https://user-images.githubusercontent.com/952836/36940356-3e4e0156-1f4a-11e8-9097-be6b507ab3fa.png">

**Comment by KjellRanda** [comment]
Thanks, cloning the repo worked.
But for some reasons it was not sufficient to restart the grafana-server.
But after a reboot for a kernel update it all worked.

Kjell

**Comment by briangann** [comment]
Clearing your browser cache would also refresh the plugin data, I ran into the same problem.

Thanks!

Brian

**Comment by AndrewStickler** [comment]
Hi Brian - any ETA for publishing the new version on grafana.com please?

**Comment by briangann** [comment]
The latest version has been published to grafana.com. I'm using it with v5.0.3 without any problems.  Are you having issues with it?

**Comment by AndrewStickler** [comment]
I upgraded my Grafana from 4.x to 5.0.4 yesterday and then upgraded your gauge to 0.0.6, but my existing dashboards show an error on the gauges, and won't let me edit those panels. However, I have tried again today and all seems OK, so must have been a browser caching issue I think. Thanks for responding.
